In [38]:
import tensorflow as tf
print(tf.__version__)

2.21.0


In [39]:
import numpy as np 
import pandas as pd
df = pd.read_csv('wine.csv')
df.head()
y=df['quality']
x=df.drop('quality',axis=1)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)


In [40]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(64,32),activation='relu',max_iter=500)
model.fit(x_train,y_train)

,"hidden_layer_sizes hidden_layer_sizes: array-like of shape(n_layers - 2,), default=(100,)The ith element represents the number of neurons in the ithhidden layer.","(64, ...)"
,"max_iter max_iter: int, default=200Maximum number of iterations. The solver iterates until convergence(determined by 'tol') or this number of iterations. For stochasticsolvers ('sgd', 'adam'), note that this determines the number of epochs(how many times each data point will be used), not the number ofgradient steps.",500
,"activation activation: {'identity', 'logistic', 'tanh', 'relu'}, default='relu'Activation function for the hidden layer.- 'identity', no-op activation, useful to implement linear bottleneck, returns f(x) = x- 'logistic', the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).- 'tanh', the hyperbolic tan function, returns f(x) = tanh(x).- 'relu', the rectified linear unit function, returns f(x) = max(0, x)",'relu'
,"solver solver: {'lbfgs', 'sgd', 'adam'}, default='adam'The solver for weight optimization.- 'lbfgs' is an optimizer in the family of quasi-Newton methods.- 'sgd' refers to stochastic gradient descent.- 'adam' refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy BaFor a comparison between Adam optimizer and SGD, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_training_curves.py`.Note: The default solver 'adam' works pretty well on relativelylarge datasets (with thousands of training samples or more) in terms ofboth training time and validation score.For small datasets, however, 'lbfgs' can converge faster and performbetter.",'adam'
,"alpha alpha: float, default=0.0001Strength of the L2 regularization term. The L2 regularization termis divided by the sample size when added to the loss.For an example usage and visualization of varying regularization, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_alpha.py`.",0.0001
,"batch_size batch_size: int, default='auto'Size of minibatches for stochastic optimizers.If the solver is 'lbfgs', the classifier will not use minibatch.When set to ""auto"", `batch_size=min(200, n_samples)`.",'auto'
,"learning_rate learning_rate: {'constant', 'invscaling', 'adaptive'}, default='constant'Learning rate schedule for weight updates.- 'constant' is a constant learning rate given by 'learning_rate_init'.- 'invscaling' gradually decreases the learning rate at each time step 't' using an inverse scaling exponent of 'power_t'. effective_learning_rate = learning_rate_init / pow(t, power_t)- 'adaptive' keeps the learning rate constant to 'learning_rate_init' as long as training loss keeps decreasing. Each time two consecutive epochs fail to decrease training loss by at least tol, or fail to increase validation score by at least tol if 'early_stopping' is on, the current learning rate is divided by 5.Only used when ``solver='sgd'``.",'constant'
,"learning_rate_init learning_rate_init: float, default=0.001The initial learning rate used. It controls the step-sizein updating the weights. Only used when solver='sgd' or 'adam'.",0.001
,"power_t power_t: float, default=0.5The exponent for inverse scaling learning rate.It is used in updating effective learning rate when the learning_rateis set to 'invscaling'. Only used when solver='sgd'.",0.5
,"shuffle shuffle: bool, default=TrueWhether to shuffle samples in each iteration. Only used whensolver='sgd' or 'adam'.",True
,"random_state random_state: int, RandomState instance, default=NoneDetermines random number generation for weights and biasinitialization, train-test split if early stopping is used, and batchsampling when solver='sgd' or 'adam'.Pass an int for reproducible results across multiple function calls.See :term:`Glossary <random_state>`.",None


In [41]:
print(model.score(x_test,y_test))

0.555


In [42]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = model.predict(x_test)

cm = confusion_matrix(y_test,y_pred)
print(cm)


[[  0   0   1   0   0   0]
 [  0   0  11   2   0   0]
 [  0   0 130  31   3   0]
 [  0   0  78  71  20   0]
 [  0   0   4  23  21   0]
 [  0   0   0   2   3   0]]


In [43]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5


In [44]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1199, 11)
(400, 11)
(1199,)
(400,)


In [45]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(64, input_dim=11, activation='relu'))


model.add(Dense(6, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])   #optimizer task - classification
#optimizer - Adam is an optimization algorithm that can be used instead of the classical stochastic
# gradient descent procedure to update network weights iteratively based on training data.
# It combines the advantages of two other extensions of stochastic gradient descent,
# namely Adaptive Gradient Algorithm (AdaGrad) and Root Mean Square Propagation (RMSProp).
#loss - The loss function used here is 'sparse_categorical_crossentropy',
# which is suitable for multi-class classification problems where the target labels are integers.
# It calculates the cross-entropy loss between the true labels and the predicted probabilities.
#metrics - The model is evaluated using the 'accuracy' metric, which measures the proportion of correctly classified samples.
model.summary()
y_train=y_train-3
#why we are doing this because the quality of wine is in the range of 3-8 and we have to convert it into 0-5 for the model to work properly.
y_test=y_test-3 
#why we are doing this because the quality of wine is in the range of 3-8 and we have to convert it into 0-5 for the model to work properly.

print(np.unique(y_train))



c:\Users\annu3\OneDrive\Desktop\aiml_Internship\aiml_internship\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 6)              │           390 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,158 (4.52 KB)

 Trainable params: 1,158 (4.52 KB)

 Non-trainable params: 0 (0.00 B)

[0 1 2 3 4 5]


In [46]:
model.fit(x_train,y_train,epochs=100,batch_size=32,validation_data=(x_test,y_test))
#validation_split- 0.2 means 20% of the training data will be used for validation.
#epochs- The model will be trained for 100 epochs, meaning it will iterate over the entire training dataset 100 times.

Epoch 1/100


38/38 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.3186 - loss: 2.8186 - val_accuracy: 0.3875 - val_loss: 1.5802
Epoch 2/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4070 - loss: 1.3942 - val_accuracy: 0.4550 - val_loss: 1.2770
Epoch 3/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4629 - loss: 1.2275 - val_accuracy: 0.4625 - val_loss: 1.2074
Epoch 4/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4737 - loss: 1.1814 - val_accuracy: 0.4925 - val_loss: 1.1767
Epoch 5/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4862 - loss: 1.1693 - val_accuracy: 0.4975 - val_loss: 1.1525
Epoch 6/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4971 - loss: 1.1519 - val_accuracy: 0.4875 - val_loss: 1.1447
Epoch 7/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4996 - loss: 1.1450 - val_accuracy: 0.4875 - val_loss: 1.1422
Epoch 8/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5029 - loss: 1.1464 - val_accuracy: 0.4425 - val_loss: 1.1

In [47]:
pred = model.predict(x_test)
pred=np.argmax(pred,axis=1)
pred=pred+3
print(pred)


13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
[5 5 5 5 6 5 5 5 6 6 6 5 6 5 5 7 5 5 7 5 5 5 6 7 5 5 6 5 5 6 5 6 6 5 5 5 7
 6 5 7 5 5 6 5 6 6 7 5 5 6 5 5 5 6 5 5 6 6 6 5 6 6 5 5 7 5 7 5 7 5 7 5 6 6
 7 5 6 6 6 6 5 7 5 5 6 7 5 6 6 5 6 7 6 5 5 6 5 6 5 6 5 5 6 7 6 7 5 5 6 5 7
 5 7 5 6 6 6 5 5 6 6 5 6 5 6 5 6 6 6 6 6 5 5 7 6 5 5 5 5 6 5 6 7 6 6 5 6 6
 6 5 6 7 5 6 6 6 5 6 6 6 7 6 7 5 5 6 5 5 5 5 5 5 6 5 7 6 7 5 5 5 5 7 5 7 5
 6 5 6 7 5 6 6 6 7 6 6 5 5 5 7 5 5 5 5 7 6 5 6 6 7 5 5 6 7 7 6 5 5 6 5 5 6
 7 7 5 5 5 6 5 6 5 5 7 6 5 7 6 6 5 5 5 5 6 6 5 5 6 5 7 5 5 6 5 5 5 5 6 6 5
 6 6 7 5 7 6 7 5 5 7 7 5 5 5 5 5 6 6 6 6 5 7 5 6 5 5 6 5 6 5 6 5 7 5 6 5 7
 5 7 7 7 5 5 6 5 5 5 6 7 7 7 6 6 5 5 5 6 5 5 6 5 5 7 6 6 5 5 6 6 5 6 6 7 5
 5 5 6 6 7 5 5 7 7 6 5 6 5 7 5 6 6 5 7 5 5 5 6 5 5 6 6 5 5 5 6 5 6 6 5 5 5
 5 5 6 5 5 7 5 6 5 5 5 6 7 5 7 7 7 5 5 6 5 6 5 5 6 6 7 5 5 6]


In [48]:
model.save('wine_quality_model.h5')